- name: Update package index
  ansible.builtin.apt:
    update_cache: true

- name: Install Java (required for Jenkins agent)
  ansible.builtin.apt:
    name: openjdk-11-jre
    state: present

- name: Create directory for Swarm client
  ansible.builtin.file:
    path: /opt/swarm-client
    state: directory
    mode: '0755'

- name: Download Swarm client JAR file
  ansible.builtin.get_url:
    url: https://repo.jenkins-ci.org/public/org/jenkinsci/plugins/swarm-client/3.18/swarm-client-3.18.jar
    dest: /opt/swarm-client/swarm-client.jar
    mode: '0644'

- name: Create systemd service file for Jenkins Swarm client
  ansible.builtin.template:
    src: jenkins-swarm-client.service.j2
    dest: /etc/systemd/system/jenkins-swarm-client.service
    mode: '0644'
  notify:
    - Reload systemd

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Ensure Jenkins Swarm client is running
  ansible.builtin.systemd:
    name: jenkins-swarm-client
    state: started
    enabled: true
