---
# tasks file for roles/helm
- name: Add Helm's Official GPG key
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    keyring: /usr/share/keyrings/helm.gpg
    state: present

- name: Add Helm repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    filename: helm-stable-debian
    state: present

- name: Update APT package index
  ansible.builtin.apt:
    update_cache: true

- name: Install Helm
  ansible.builtin.apt:
    name: helm
    state: present
